import { z } from "zod";
import { pgTable, text, jsonb, timestamp, integer, primaryKey, boolean } from "drizzle-orm/pg-core";

// Database tables (Drizzle ORM)
export const gameSessions = pgTable("game_sessions", {
  id: text("id").primaryKey(),
  state: jsonb("state"),
  ended: boolean("ended").default(false).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const usageTracking = pgTable("usage_tracking", {
  year: integer("year").notNull(),
  month: integer("month").notNull(),
  turnsUsed: integer("turns_used").notNull().default(0),
}, (table) => ({
  pk: primaryKey({ columns: [table.year, table.month] }),
}));

// Game configuration options
export const spanishLevels = ["A2", "B1", "B2"] as const;
export type SpanishLevel = typeof spanishLevels[number];

export const durations = ["corta", "media", "larga"] as const;
export type Duration = typeof durations[number];

export const inputModes = ["Acción", "Pregunta"] as const;
export type InputMode = typeof inputModes[number];

export const dangerLevels = ["bajo", "medio", "alto"] as const;
export type DangerLevel = typeof dangerLevels[number];

// Duration to target turns mapping
export const durationToTurns: Record<Duration, number> = {
  corta: 12,
  media: 25,
  larga: 45,
};

// Plot hook generated by AI
export const plotHookSchema = z.object({
  id: z.string(),
  titulo: z.string(),
  descripcion: z.string(),
});
export type PlotHook = z.infer<typeof plotHookSchema>;

// AI response option
export const optionSchema = z.object({
  id: z.enum(["A", "B", "C", "D"]),
  texto: z.string(),
});
export type GameOption = z.infer<typeof optionSchema>;

// Inventory state
export const inventorySchema = z.object({
  items: z.array(z.string()),
  pistas: z.array(z.string()),
});
export type Inventory = z.infer<typeof inventorySchema>;

// Danger indicator
export const peligroSchema = z.object({
  nivel: z.enum(dangerLevels),
  razon: z.string(),
});
export type Peligro = z.infer<typeof peligroSchema>;

// State change from action
export const cambioEstadoSchema = z.object({
  salud_delta: z.number().optional(),
  estado_afectos_agregar: z.array(z.string()).optional(),
  estado_afectos_quitar: z.array(z.string()).optional(),
  banderas_agregar: z.array(z.string()).optional(),
  banderas_quitar: z.array(z.string()).optional(),
});
export type CambioEstado = z.infer<typeof cambioEstadoSchema>;

// Learning log entry
export const learningEntrySchema = z.object({
  tipo: z.enum(["correccion", "pregunta", "pista"]),
  contenido: z.string(),
  turno: z.number(),
});
export type LearningEntry = z.infer<typeof learningEntrySchema>;

// Learning summary at game end
export const resumenAprendizajesSchema = z.object({
  puntos: z.array(z.string()),
  errores_frecuentes: z.array(z.string()),
  frases_utiles: z.array(z.string()),
});
export type ResumenAprendizajes = z.infer<typeof resumenAprendizajesSchema>;

// AI response format (extended with consequences)
export const aiResponseSchema = z.object({
  narracion: z.string(),
  opciones: z.array(optionSchema).min(0).max(4),
  permitir_texto_libre: z.boolean(),
  permitir_preguntas: z.boolean(),
  pista_profesor: z.string().optional(),
  inventario: z.object({
    agregar: z.array(z.string()).optional(),
    quitar: z.array(z.string()).optional(),
  }).optional(),
  estado: z.object({
    progreso: z.number().min(0).max(1),
    tension: z.number().min(0).max(1),
  }),
  resumen_memoria: z.string(),
  consecuencia: z.string().optional(),
  peligro: peligroSchema.optional(),
  cambio_estado: cambioEstadoSchema.optional(),
  game_over: z.boolean().optional(),
  game_over_razon: z.string().optional(),
  final: z.boolean().optional(),
  final_razon: z.string().optional(),
  resumen_aprendizajes: resumenAprendizajesSchema.optional(),
});
export type AIResponse = z.infer<typeof aiResponseSchema>;

// Turn history entry (extended)
export const turnEntrySchema = z.object({
  turnNumber: z.number(),
  userInput: z.string(),
  inputMode: z.enum(inputModes),
  narracion: z.string(),
  opciones: z.array(optionSchema),
  pistaProfesor: z.string().optional(),
  timestamp: z.number(),
  consecuencia: z.string().optional(),
  peligro: peligroSchema.optional(),
});
export type TurnEntry = z.infer<typeof turnEntrySchema>;

// Game state (extended with health, status effects, flags)
export const gameStateSchema = z.object({
  sessionId: z.string(),
  spanishLevel: z.enum(spanishLevels),
  duration: z.enum(durations),
  targetTurns: z.number(),
  turnIndex: z.number(),
  progreso: z.number(),
  tension: z.number(),
  plot: plotHookSchema,
  inventory: inventorySchema,
  resumenMemoria: z.string(),
  history: z.array(turnEntrySchema),
  currentOptions: z.array(optionSchema),
  permitirTextoLibre: z.boolean(),
  permitirPreguntas: z.boolean(),
  currentNarracion: z.string(),
  currentPista: z.string().optional(),
  gameEnded: z.boolean(),
  salud: z.number().min(0).max(100),
  estadoAfectos: z.array(z.string()),
  banderas: z.array(z.string()),
  learningLog: z.array(learningEntrySchema),
  currentPeligro: peligroSchema.optional(),
  currentConsecuencia: z.string().optional(),
  gameOverRazon: z.string().optional(),
  finalRazon: z.string().optional(),
  resumenAprendizajes: resumenAprendizajesSchema.optional(),
});
export type GameState = z.infer<typeof gameStateSchema>;

// API request/response types
export interface StartRequest {
  spanishLevel: SpanishLevel;
  duration: Duration;
}

export interface StartResponse {
  sessionId: string;
  plots: PlotHook[];
}

export interface SelectPlotRequest {
  sessionId: string;
  plotId: string;
  spanishLevel: SpanishLevel;
  duration: Duration;
}

export interface SelectPlotResponse {
  gameState: GameState;
}

export interface TurnRequest {
  sessionId: string;
  mode: InputMode;
  userInput?: string;
  selectedOptionId?: string;
  state: {
    spanishLevel: SpanishLevel;
    duration: Duration;
    targetTurns: number;
    turnIndex: number;
    progreso: number;
    tension: number;
    plot: PlotHook;
    inventory: Inventory;
    resumenMemoria: string;
    salud: number;
    estadoAfectos: string[];
    banderas: string[];
  };
  recentHistory: TurnEntry[];
}

export interface TurnResponse {
  aiResponse: AIResponse;
  gameEnded: boolean;
  isPreguntaResponse?: boolean;
  grammarFeedback?: string;
}

// Legacy user schema (keep for compatibility)
export const users = {
  id: "",
  username: "",
  password: "",
};
export type User = { id: string; username: string; password: string };
export type InsertUser = { username: string; password: string };
