import { z } from "zod";

// Game configuration options
export const spanishLevels = ["A2", "B1", "B2"] as const;
export type SpanishLevel = typeof spanishLevels[number];

export const durations = ["corta", "media", "larga"] as const;
export type Duration = typeof durations[number];

export const inputModes = ["Acción", "Pregunta"] as const;
export type InputMode = typeof inputModes[number];

// Duration to target turns mapping
export const durationToTurns: Record<Duration, number> = {
  corta: 12,
  media: 25,
  larga: 45,
};

// Plot hook generated by AI
export const plotHookSchema = z.object({
  id: z.string(),
  titulo: z.string(),
  descripcion: z.string(),
});
export type PlotHook = z.infer<typeof plotHookSchema>;

// AI response option
export const optionSchema = z.object({
  id: z.enum(["A", "B", "C", "D"]),
  texto: z.string(),
});
export type GameOption = z.infer<typeof optionSchema>;

// Inventory state
export const inventorySchema = z.object({
  items: z.array(z.string()),
  pistas: z.array(z.string()),
});
export type Inventory = z.infer<typeof inventorySchema>;

// AI response format
export const aiResponseSchema = z.object({
  narracion: z.string(),
  opciones: z.array(optionSchema).min(2).max(4),
  permitir_texto_libre: z.boolean(),
  permitir_preguntas: z.boolean(),
  pista_profesor: z.string().optional(),
  inventario: z.object({
    agregar: z.array(z.string()).optional(),
    quitar: z.array(z.string()).optional(),
  }).optional(),
  estado: z.object({
    progreso: z.number().min(0).max(1),
    tension: z.number().min(0).max(1),
  }),
  resumen_memoria: z.string(),
});
export type AIResponse = z.infer<typeof aiResponseSchema>;

// Turn history entry
export const turnEntrySchema = z.object({
  turnNumber: z.number(),
  userInput: z.string(),
  inputMode: z.enum(inputModes),
  narracion: z.string(),
  opciones: z.array(optionSchema),
  pistaProfesor: z.string().optional(),
  timestamp: z.number(),
});
export type TurnEntry = z.infer<typeof turnEntrySchema>;

// Game state
export const gameStateSchema = z.object({
  sessionId: z.string(),
  spanishLevel: z.enum(spanishLevels),
  duration: z.enum(durations),
  targetTurns: z.number(),
  turnIndex: z.number(),
  progreso: z.number(),
  tension: z.number(),
  plot: plotHookSchema,
  inventory: inventorySchema,
  resumenMemoria: z.string(),
  history: z.array(turnEntrySchema),
  currentOptions: z.array(optionSchema),
  permitirTextoLibre: z.boolean(),
  permitirPreguntas: z.boolean(),
  currentNarracion: z.string(),
  currentPista: z.string().optional(),
  gameEnded: z.boolean(),
});
export type GameState = z.infer<typeof gameStateSchema>;

// API request/response types
export interface StartRequest {
  spanishLevel: SpanishLevel;
  duration: Duration;
}

export interface StartResponse {
  sessionId: string;
  plots: PlotHook[];
}

export interface SelectPlotRequest {
  sessionId: string;
  plotId: string;
  spanishLevel: SpanishLevel;
  duration: Duration;
}

export interface SelectPlotResponse {
  gameState: GameState;
}

export interface TurnRequest {
  sessionId: string;
  mode: InputMode;
  userInput?: string;
  selectedOptionId?: string;
  state: {
    spanishLevel: SpanishLevel;
    duration: Duration;
    targetTurns: number;
    turnIndex: number;
    progreso: number;
    tension: number;
    plot: PlotHook;
    inventory: Inventory;
    resumenMemoria: string;
  };
  recentHistory: TurnEntry[];
}

export interface TurnResponse {
  aiResponse: AIResponse;
  gameEnded: boolean;
  isPreguntaResponse?: boolean;
}

// Legacy user schema (keep for compatibility)
export const users = {
  id: "",
  username: "",
  password: "",
};
export type User = { id: string; username: string; password: string };
export type InsertUser = { username: string; password: string };
